version: '3'
services:
  app:
    build: ./app/
    command: ["sh", "-c", "sleep 15 && pnpm dev:docker"]
    restart: always
    depends_on:
      - server
    ports:
      - '5181:5181'

  server:
    build: ./server/
    restart: always
    depends_on:
      - database
    ports:
      - '5171:5171'

  database:
    build: ./database/
    restart: always
    ports:
      - '5202:3306'

